### ISSUE TITLE
Support for condition matching

### ISSUE THREAD

**Issue by arlando** [SwingDev/s3-browser-direct-upload#1]
I want to be able to use condition matching for keys and other things. Currently the API does not expose a conditions option and some of the required options has a type of a string which does not match the array required for conditions. Would code this in but I'm not sure if condition matching is supported for the other end points (get, put).

[Amazon condition matching documents.](http://docs.aws.amazon.com/AmazonS3/latest/dev/HTTPPOSTForms.html#ConditionMatching)

I think the API could look like this:

```javascript
{
key: String // optional
conditions: [[] ..[]] // an array of arrays of condition matches
}
...
[
["condition", "<key0>", "pattern"],
...
["condition", "<key1>", "pattern"]
]
}
```

The script could process by mapping the <keys> to an conditional object: ```{key0: ["condition", "<key0>", "pattern"]}``` checking that if a required key does not exist in the options, if it exists in the conditional its ok. A single key may have multiple conditions, we should just append the conditions array to the conditions on the policy. Not sure if this feature exists already.

**Comment by gabrieloczkowski** [comment]
Hi.
I've added support for condition matching (all types).
[Release 0.1.2](https://github.com/SwingDev/s3-browser-direct-upload/releases/tag/v0.1.2)
[061ce697ea4edbb40b554b6059b598bca7e4909a](https://github.com/SwingDev/s3-browser-direct-upload/commit/061ce697ea4edbb40b554b6059b598bca7e4909a)

Apologize for the long wait (got a lot of stuff to do, and those changes needs testing) :)
Let me know if everything is ok.

**Comment by arlando** [comment]
Thanks @gabrieloczkowski!
