### ISSUE TITLE
Issues Using This With FormData?

### ISSUE THREAD

**Issue by joshdickson40** [SwingDev/s3-browser-direct-upload#4]
Not sure if this is an issue related to this library, but I've run out of ideas and am curious if anyone has seen any similar issues.

I'm using uploadPostForm. Everything seems to go fine (the policy is generated, etc), but when I get it back on the client side, using the info provided results in a 403 from AWS saying SignatureDoesNotMatch, "The request signature we calculated does not match the signature you provided. Check your key and signing method." I've checked secret key for accuracy, I even created a new set of credentials to make sure something didn't go wrong. 

Is there something I'm doing wrong regarding configuring that key that's resulting in this SignatureDoesNotMatch error? I have double and triple checked to make sure I am using the correct form attributes (key, AWSAccessKeyId, acl, policy, and signature), and I am using the generated x-amz-signature. I'm sure it's something small and dumb, just can't think of what it might be.

If anyone else has run into this, I'd love to know what the fix was.

**Comment by joshdickson40** [comment]
My error. Most of the tutorials for this are apparently for v2, and this is v4.

In v4, you are setting a number of x-amz-* fields, and not setting an id or signature field directly. This library then uses the correct things for v4, but you need to set v4 attributes on the FormData object, not v2.

**Comment by simonemazzoni** [comment]
@joshdickson40 I had a similar problem too.
What do you mean saying the following?

> but you need to set v4 attributes on the FormData object, not v2.

What are the "FormData"?

Thanks
